PL_MVC/Controllers/EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ML;

namespace MVC.Controllers
{
    public class EmpresaController : Controller
    {
        Result result = new Result();

        /// <summary>
        /// GET: Traemos los registros de la tabla empresa
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Empresa empresa = new ML.Empresa();
            result = BL.Empresa.GetAllEF(empresa);
            ViewBag.Message = result.Message;
            if (result.Correct && result.Objects.Count > 0)
            {
                //IEnumerable<ModelLayer.Usuario> usuarios = result.Objects.OfType<ModelLayer.Usuario>().ToList();
               
                empresa.Empresas = result.Objects;
                return View(empresa);
            }
            return View("/");
        }


        [HttpPost]
        public ActionResult GetAll(ML.Empresa empresa)
        {
            ML.Result result = BL.Empresa.GetAllEF(empresa);

            ViewBag.Message = result.Message;
            if (result.Correct && result.Objects.Count > 0)
            {
                empresa = new ML.Empresa();
                empresa.Empresas = result.Objects;

            }
            else
            {
                empresa = new ML.Empresa();
                empresa.Empresas = new List<object> { };
            }
            return View(empresa);
        }

        public ActionResult Delete(int? IdEmpresa)
        {
            if (IdEmpresa == null)
            {
                return Redirect("/Empresa/GetAll");
            }
            else
            {
                result = BL.Empresa.DeleteEF(IdEmpresa.Value);
                ViewBag.Message = result.Message;
                if (result.Correct)
                {
                    // return Redirect("/Usuario/GetAll");
                }
            }
            return PartialView("Modal");
        }

        /// <summary>
        /// Usaremos la misma vista para ADD y UPDATE por ello validamos si
        /// al invocar al controller se le envía el parámetro del ID
        /// </summary>
        /// <param name="IdEmpresa"></param>
        /// <returns>View</returns>
        [HttpGet]
        public ActionResult Form(int? IdEmpresa)
        {
            ML.Empresa empresa = new ML.Empresa();
            if (IdEmpresa == null)
            {
                return View(empresa);
            }
            else
            {
                /// GETBYID
                result = BL.Empresa.GetByIdEF(IdEmpresa.Value);
                ViewBag.Message = result.Message;
                if (result.Correct && result.Object != null)
                {
                    empresa = (ML.Empresa)result.Object;
                }
                return View(empresa);
            }
        }
        /// <summary>
        /// Como es la misma vista evaluamos si es un ADD o UPDATE
        /// y sin importar sera enviado a un Modal de un PartialView
        /// </summary>
        /// <param name="empresa"></param>
        /// <returns>PartialView</returns>
        [HttpPost]
        public ActionResult Form(ML.Empresa empresa)
        {
            // ADD
            if (empresa.IdEmpresa == 0)
            {
                if (empresa != null)
                {
                    result = BL.Empresa.AddEF(empresa);
                    ViewBag.Message = result.Message;
                    if (result.Correct)
                    {
                        ModelState.Clear();
                    }
                }
            }
            else
            // UPDATE
            {
                if (empresa != null)
                {
                    result = BL.Empresa.UpdateEF(empresa);
                    ViewBag.Message = result.Message;
                    if (result.Correct)
                    {
                        ModelState.Clear();
                    }
                }
            }
            return PartialView("Modal");
        }
    }
}

PL_MVC/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;
using BL;
using ML;
using Newtonsoft.Json;

namespace MVC.Controllers
{
    public class UsuarioController : Controller
    {
        string urlAPI = System.Configuration.ConfigurationManager.AppSettings["DBernalProgramacionNCapas"];


        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string user_name, string password)
        {

            return View();
        }

        Result result = new Result();
        [HttpGet]
        public ActionResult GetAll()
        {
            //ModelLayer.Usuario user = new ModelLayer.Usuario();
            //user.Rol = new ModelLayer.Rol();

            //ModelLayer.Result result = BusinessLayer.Usuario.GetAllEF(user);
            //Result resultRoles = BusinessLayer.Rol.GetAllEF();

            //ViewBag.Message = result.Message;

            //if (result.Correct && result.Objects.Count > 0 && resultRoles.Correct)
            //{
            //    //IEnumerable<ModelLayer.Usuario> usuarios = result.Objects.OfType<ModelLayer.Usuario>().ToList();
            //    ModelLayer.Usuario usuario = new ModelLayer.Usuario();
            //    usuario.Rol = new ModelLayer.Rol();
            //    usuario.Rol.Roles = resultRoles.Objects;

            //    usuario.Usuarios = result.Objects;
            //    return View(usuario);
            //}
            //return View("/");


            ML.Result result = new ML.Result();
            try
            {
                using (HttpClient httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Clear();
                    httpClient.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

                    httpClient.BaseAddress = new Uri(urlAPI);


                    //Sending request to find web api REST service resource using HttpClient
                    var request = httpClient.GetAsync("Usuario/GetAll");
                    request.Wait();

                    //Checking the response is successful or not which is sent using HttpClient
                    var response = request.Result;
                    if (response.IsSuccessStatusCode)
                    {
                        var readContent = response.Content.ReadAsStringAsync().Result;

                        ML.Result resultAPI = JsonConvert.DeserializeObject<ML.Result>(readContent);

                        result.Message = resultAPI.Message;

                        if (resultAPI.Correct)
                        {
                            result.Objects = new List<object>();
                            foreach (var item in resultAPI.Objects)
                            {
                                ML.Usuario user = JsonConvert.DeserializeObject<ML.Usuario>(item.ToString());
                                result.Objects.Add(user);
                            }
                            result.Correct = true;
                        }
                    }
                }
            }
            catch (Exception error)
            {
                result.Correct = false;
                result.Message = error.Message;
            }


            ViewBag.Message = result.Message;

            ML.Usuario usuario = new ML.Usuario();
            usuario.Rol = new ML.Rol();

            Result resultRoles = BL.Rol.GetAllEF();
            usuario.Rol.Roles = resultRoles.Objects;

            if (result.Correct)
            {
                usuario.Usuarios = result.Objects;
            }
            else
            {
                usuario.Usuarios = new List<object> { };
            }
            return View(usuario);
        }

        [HttpPost]
        public ActionResult GetAll(ML.Usuario usuario)
        {
            //ModelLayer.Result result = BusinessLayer.Usuario.GetAllEF(usuario);
            //Result resultRoles = BusinessLayer.Rol.GetAllEF();
            //ViewBag.Message = result.Message;
            //if (result.Correct && result.Objects.Count > 0 && resultRoles.Correct)
            //{
            //    //IEnumerable<ModelLayer.Usuario> usuarios = result.Objects.OfType<ModelLayer.Usuario>().ToList();
            //    usuario = new ModelLayer.Usuario();
            //    usuario.Rol = new ModelLayer.Rol();
            //    usuario.Rol.Roles = resultRoles.Objects;

            //    usuario.Usuarios = result.Objects;
            //    return View(usuario);
            //}
            //return View("/");


            ML.Result result = new ML.Result();
            try
            {
                using (HttpClient httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Clear();
                    httpClient.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                    httpClient.BaseAddress = new Uri(urlAPI);


                    HttpContent content = new StringContent(JsonConvert.SerializeObject(usuario), Encoding.UTF8, "application/json");

                    //Sending request to find web api REST service resource using HttpClient
                    var request = httpClient.PostAsync("Usuario/GetAll", content);
                    request.Wait();

                    //Checking the response is successful or not which is sent using HttpClient
                    var response = request.Result;
                    if (response.IsSuccessStatusCode)
                    {
                        var readContent = response.Content.ReadAsStringAsync().Result;

                        ML.Result resultAPI = JsonConvert.DeserializeObject<ML.Result>(readContent);

                        result.Message = resultAPI.Message;

                        if (resultAPI.Correct)
                        {
                            result.Objects = new List<object>();
                            foreach (var item in resultAPI.Objects)
                            {
                                ML.Usuario user = JsonConvert.DeserializeObject<ML.Usuario>(item.ToString());
                                result.Objects.Add(user);
                            }
                            result.Correct = true;
                        }
                    }
                }
            }
            catch (Exception error)
            {
                result.Correct = false;
                result.Message = error.Message;
            }


            ViewBag.Message = result.Message;
            Result resultRoles = BL.Rol.GetAllEF();

            usuario.Rol = new ML.Rol();
            usuario.Rol.Roles = resultRoles.Objects;

            if (result.Correct)
            {
                usuario.Usuarios = result.Objects;
            }
            else
            {
                usuario.Usuarios = new List<object> { };
            }
            return View(usuario);
        }

        [HttpGet]
        public ActionResult GetById(int? IdUsuario)
        {
            if (IdUsuario == null)
            {
                return Redirect("/Usuario/GetAll");
            }
            else
            {
                ML.Usuario usuario = new ML.Usuario();
                result = BL.Usuario.GetByIdEF(IdUsuario.Value);
                ViewBag.Message = result.Message;
                if (result.Correct && result.Object != null)
                {
                    usuario = (ML.Usuario)result.Object;
                    return PartialView("GetById", usuario);
                }
            }
            return PartialView("GetById");
        }
        public ActionResult Delete(int? IdUsuario)
        {
            if (IdUsuario == null)
            {
                return Redirect("/Usuario/GetAll");
            }
            else
            {
                result = BL.Usuario.DeleteEF(IdUsuario.Value);
                ViewBag.Message = result.Message;
                if (result.Correct)
                {
                    // return Redirect("/Usuario/GetAll");
                }
            }
            return PartialView("Modal");
        }


        [HttpGet]
        public ActionResult Form(int? IdUsuario)
        {
            Result resultRoles = BL.Rol.GetAllEF();
            Result resultPaises = BL.Pais.GetAll();


            if (resultRoles.Correct && resultPaises.Correct)
            {
                // Instanciamos un objeto alumno
                ML.Usuario usuario = new ML.Usuario();

                // Inicializamos los objetos que hacen referencia a la información del usuario.
                usuario.Rol = new ML.Rol();
                usuario.Direccion = new ML.Direccion();
                usuario.Direccion.Colonia = new ML.Colonia();
                usuario.Direccion.Colonia.Municipio = new ML.Municipio();
                usuario.Direccion.Colonia.Municipio.Estado = new ML.Estado();
                usuario.Direccion.Colonia.Municipio.Estado.Pais = new ML.Pais();

                if (IdUsuario == null)
                {
                    // Pasamos esos parámetros a nuestros objetos
                    usuario.Direccion.Colonia.Municipio.Estado.Pais.Paises = resultPaises.Objects;
                    usuario.Rol.Roles = resultRoles.Objects;
                    // ADD

                }
                else
                {
                    ML.Result result = BL.Usuario.GetByIdEF(IdUsuario.Value);
                    ViewBag.Message = result.Message;
                    // GET BY ID
                    if (result.Correct && result.Object != null)
                    {
                        // Igualamos el objeto usuario con lo obtenido en la consulta
                        usuario = (ML.Usuario)result.Object;

PL_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Aseguradora ASP.NET</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">



    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">


    <!-- JavaScript Bundle with Popper -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>


    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">Aseguradora</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    @*<li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="@Url.Action("Index", "Home")">Home</a>
                        </li>*@

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Usuario
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="@Url.Action("GetAll", "Usuario")">Ver Usuarios</a></li>

                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="@Url.Action("Form", "Usuario")">Registrar</a></li>
                        </ul>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="@Url.Action("GetAll", "Empresa")">Empresa</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="@Url.Action("GetAll", "Aseguradora")">Aseguradora</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="@Url.Action("About", "Home")">Acerca de</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="@Url.Action("Contact", "Home")">Contacto</a>
                    </li>

                </ul>

            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()

        <div style="bottom: 0; ">
            <hr style="width:100%;" />
            <footer>
                <p>&copy; @DateTime.Now.Year - Aseguradora ASP.NET</p>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)

    @section Scrips{
        <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
    }
</body>
</html>